1. bug in document(). error returns for VCFArray(seed) after document(): 

-- issue identified as bug in `devtools`: https://github.com/r-lib/devtools/issues/1845
-- workaround now. export `DelayedUnaryOp` and `DelayedOp` classes from `DelayedArray` package (locally modified and installed. install.packages("/home/qian/Documents/Research/DelayedArray", repos=NULL)).

```{r}
seed <- VCFArraySeed(fl, name = "GL")
VCFArray(seed)
## Error in validObject(.Object) : invalid class “DelayedMatrix” object: 
##     'x' must have exactly 2 dimensions
traceback()
## 10: stop(msg, ": ", errors, domain = NA)
## 9: validObject(.Object)
## 8: initialize(value, ...)
## 7: initialize(value, ...)
## 6: new(...)
## 5: new2(Class, seed = seed)
## 4: new_DelayedArray(seed, Class = "VCFArray") at VCFArray-class.R#104
## 3: DelayedArray(seed)
## 2: DelayedArray(seed) at VCFArray-class.R#131
## 1: VCFArray(seed)
```

2. Remove the `Rsamtools` from `DESCRIPTION, Imports` for now. Because the `Rsamtools::countTabix()` function is remove from our script.   -- done!

3. VCFArraySeed(file = "VCFFile")  -- done!
- if (!is.na(index(file)) && length(index)) stop()
- if (is.na(index(file)) && length(index) ) index(file) = index
- if (is.na(index(file)) && !length(index) ) index(file) = paste0(path(file), ".tbi")

4. save header info into `VCFArraySeed`. 
- to extract the header info, geno(header)$Type in `extract_array`. 
- fail if `VCFArray(name=NULL)` later in `VCFArraySeed(name = )` checking. 
- extract the possible 3rd dimension of `VCFArraySeed` and save as @dim slot. 

4. VCFArraySeed(file = "VCFStack")
- ## need to convert VCFStack => VCFFile (combined). -- not practical. 
- Check ?readVcfStack: lapply to each individual VCFFile and then rbind the VCF files. 
- use readVCFStack(param = ) in VCFArraySeed() constructor. 
- only takes in `RangedVcfStack` object, because it has the rowRanges() available, which is required for the `VCFArraySeed` constructor. 

Martin: 

1. add method of scanVcfHeader::VcfStack, to return the shared header info for all VcfFile objects inside the VcfStack object. 



